### ISSUE TITLE
How to get the all ENV parameters?

### ISSUE THREAD

**Issue by wade-liwei** [imperatrona/twitter-scraper#7]
authToken     = os.Getenv("AUTH_TOKEN")
	csrfToken     = os.Getenv("CSRF_TOKEN")
	cookies       = os.Getenv("COOKIES")
	username      = os.Getenv("TWITTER_USERNAME")
	password      = os.Getenv("TWITTER_PASSWORD")
	email         = os.Getenv("TWITTER_EMAIL")
	
	I just know the username and password value.

**Comment by imperatrona** [comment]
You probably don't need them all.
`cookies` for reusing your session, so you don't get banned caused by frequent log in. you can get it from your browser and use instead `username` and `password`
`authToken` and `csrfToken` is another way to keep your session, it's basically the same as `cookies` cause auth_token and csrf token (ct0) is keept in cookies.
`email` is for when account have email confirmation.

you can choose to only use `authToken` + `csrfToken` or `cookies` or `username` + `password` method

**Comment by wade-liwei** [comment]
Got it. Thank you so much.

Is there a users list that have liked a Tweet and a users list that have Retweeted a Tweet?

**Comment by wade-liwei** [comment]
I can not see who liked someone else's tweets.

https://www.quora.com/How-can-I-see-who-liked-someone-elses-tweets-on-X
On Twitter, you can't directly see who liked someone else's tweets. However, you can see the total number of likes a tweet has received by clicking on the like icon (heart symbol) below the tweet. You won't be able to see a list of specific users who liked the tweet unless you're the owner of the tweet or the account that liked it.

I am not sure who is the account that liked it.


but I can implement call interface with the domain(twitter.com).

**Comment by wade-liwei** [comment]
Can I  be able to see a list of specific users with a Oauth login?

I want to try the method.

**Comment by imperatrona** [comment]
@wade-liwei twitter removed liked list couple months ago, so there's no possible way to see who liked the post. retweets and quotes still available.

the reason our links is diffrent is because twitter have diffrent versions of their api available, when they update api they just create new id for endpoint. you can use older/newer endpoints as long as you pass params requred

**Comment by wade-liwei** [comment]
Got it. Thank you. good man.
